# Generated by Django 2.2.3 on 2019-07-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteEM', '0002_auto_20190718_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='retorno',
            name='nome',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='session',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
