# Generated by Django 2.2.3 on 2019-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteEM', '0003_auto_20190719_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='retorno',
            name='mapaFreq',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='retorno',
            name='mapaRisco',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
