# Generated by Django 2.2.3 on 2019-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteEM', '0004_auto_20190719_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
    ]
